### PR TITLE
core: Create `getInputList` utility

### PR DESCRIPTION
**Pull request by kiprasmel**
Inspired by https://github.com/actions/cache/blob/master/src/restore.ts#L30-L33

Would fix https://github.com/actions/toolkit/issues/184,

but there's another issue - https://github.com/actions/cache/issues/44:
an input list should use arrays instead of strings,
separated by newlines (`\n`).

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
yeah, I think the real list type would be cooperative with the yaml, the service and come down in the job message to the runner as a line delimited or array of strings.

**Comment by sarpik** [comment]
@bryanmacfarlane I agree - let's not rush this.

**Comment by abhilash1in** [comment]
@bryanmacfarlane why do you think this may not be the right path?

**Comment by KaelWD** [comment]
This would be useful for me, I'm trying to upload ignored files as artefacts but `actions/upload-artifact` doesn't support a newline-delimited string:

```yml
- run: echo ::set-env name=GITHUB_ARTIFACTS_LOCATIONS::$(git status --ignored --porcelain | grep -oP '(?!.*node_modules\/.*)\!\! \K.*')
- uses: actions/upload-artifact@v2
  with:
    path: ${{ env.GITHUB_ARTIFACTS_LOCATIONS }}
```

```
##[warning]No files were found for the provided path: packages/vuetify/es5/ packages/vuetify/lib-temp/ packages/vuetify/lib/. No artifacts will be uploaded.
```

**Comment by mmagician** [comment]
Any updates on this feature?

**Comment by thboop** [comment]
Hey @kiprasmel , thanks for the contribution, I've made some minor updates and created: https://github.com/actions/toolkit/pull/829/files

Going to merge that pr and release a new version this week. Going to close this out in favor of that.

**Comment by kiprasmel** [comment]
Hey @thboop, that's great - thanks!

**Pull request closed without merging**
