### PR TITLE
Upgrade uuid

### LINKED ISSUE #925: Avoid using deprecated version of UUID
All versions of the UUID npm package < 7 have [been deprecated](https://github.com/uuidjs/uuid/issues/572) due to a weakness in `Math.random()`. There are two packages in this repository that use the deprecated version.

- https://github.com/actions/toolkit/blob/main/packages/tool-cache/package.json#L44
- https://github.com/actions/toolkit/blob/main/packages/cache/package.json#L48

Any downstream package that depends on these packages will include the following line in their `package-lock.json`:

```
      "deprecated": "Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.",
```

Can you upgrade node UUID to the latest released version? Happy to submit a PR to help you out.

### PR DESCRIPTION
**Pull request by daveisfera**
Fixes #925

### CODE REVIEW

**Comment by peterdeme** [comment]
Bump to this 👀

**Comment by Kurt-von-Laven** [comment]
Yarn v4 was released on October 22nd, and `yarn npm audit --all --recursive` doesn't pass on packages such as `@actions/cache` that depend on deprecated packages like `uuid` v6 and earlier.

```
└─ uuid
   ├─ ID: uuid (deprecation)
   ├─ Issue: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
   ├─ Severity: moderate
   ├─ Vulnerable Versions: 3.4.0
   │ 
   ├─ Tree Versions
   │  └─ 3.4.0
   │ 
   └─ Dependents
      └─ @actions/cache@npm:3.2.2
```

**Review by joshmgross — COMMENTED** [review]
👋 Thank you for your contribution!

As suggested by https://github.com/actions/toolkit/pull/1571#issuecomment-1891009808 and https://github.com/actions/toolkit/issues/925#issuecomment-2061536804, I think it would be best to remove this dependency entirely in favor of the built-in `crypto.randomUUID`.

I put up a PR with that change #1824

**Comment by joshmgross** [comment]
Replaced by #1824

**Pull request closed without merging**
