### PR TITLE
Use import {Octokit}

### PR DESCRIPTION
**Pull request by nwtgck**
Hi,

The purpose of this PR  is to remove the following error.

```
node_modules/@actions/github/lib/github.d.ts:2:8 - error TS2613: Module '"/.../node_modules/@octokit/rest/index"' has no default export. Did you mean to use 'import { Octokit } from "/.../node_modules/@octokit/rest/index"' instead?

2 import Octokit from '@octokit/rest';
         ~~~~~~~
```

### CODE REVIEW

**Comment by xt0rted** [comment]
This change was made i n [v16.43.1](https://github.com/octokit/rest.js/releases/tag/v16.43.1) but the version in package.json is v16.15.0 which is why all the builds failed.

**Comment by nwtgck** [comment]
@xt0rted Thanks! Umm... Interesting...

Actually, my project using `@actions/github` fails in build-time when `import Octokit from '@octokit/rest';` is used. To avoid this, I manually modify .d.ts in node_modules: <https://github.com/nwtgck/actions-netlify/issues/2>.

**Comment by nwtgck** [comment]
I may find the reason.
> 16.43.1 (2020-02-03)
> Bug Fixes
> TypeScript: named { Octokit } export (486eadd)

<https://github.com/octokit/rest.js/releases/tag/v16.43.1>

**Comment by technote-space** [comment]
`^16.15.0` = `16.x`
so `v16.43.1` is installed.

After adding the `skipLibCheck` settings, you can build with tsc.

tsconfig.json
```
{
  "compilerOptions": {
    "skipLibCheck": true,

   ...

  }
}
```

**Comment by nwtgck** [comment]
@technote-space Thank you very much for your useful tip: `skipLibCheck`. I didn't know that.

**Comment by joshmgross** [comment]
This resolves https://github.com/actions/toolkit/issues/333

**Pull request merged**
