### PR TITLE
package-lock.json: update handlebars & uglify-js

### PR DESCRIPTION
**Pull request by francisfuzz**
### Summary

This PR updates `package-lock.json` with changes generated by `npm audit fix`.

#### Context

On a fresh clone of this repo at https://github.com/actions/toolkit/commit/a11539e1db495a98e3e8fd45249cc1e0ffddf1cd, changing directory into the repo and running `npm install` produces the following warning:

```
> npm i

> fsevents@1.2.11 install {redacted}
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
added 1409 packages from 598 contributors and audited 930414 packages in 38.148s
found 9 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

Here's the output of `npm audit`:

<details>

```
                                                                               
                       === npm audit security report ===                        
                                                                                
# Run  npm update handlebars --depth 7  to resolve 9 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > @jest/core > @jest/reporters >             │
│               │ istanbul-reports > handlebars                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1316                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lerna [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lerna > @lerna/publish > @lerna/version >                    │
│               │ @lerna/conventional-commits > conventional-changelog-core >  │
│               │ conventional-changelog-writer > handlebars                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1316                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lerna [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lerna > @lerna/version > @lerna/conventional-commits >       │
│               │ conventional-changelog-core > conventional-changelog-writer  │
│               │ > handlebars                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1316                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > @jest/core > @jest/reporters >             │
│               │ istanbul-reports > handlebars                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1324                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lerna [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lerna > @lerna/publish > @lerna/version >                    │
│               │ @lerna/conventional-commits > conventional-changelog-core >  │
│               │ conventional-changelog-writer > handlebars                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1324                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary Code Execution                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lerna [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lerna > @lerna/version > @lerna/conventional-commits >       │
│               │ conventional-changelog-core > conventional-changelog-writer  │
│               │ > handlebars                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1324                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > @jest/core > @jest/reporters >             │
│               │ istanbul-reports > handlebars                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1325                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lerna [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lerna > @lerna/publish > @lerna/version >                    │
│               │ @lerna/conventional-commits > conventional-changelog-core >  │
│               │ conventional-changelog-writer > handlebars                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1325                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lerna [dev]                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lerna > @lerna/version > @lerna/conventional-commits >       │
│               │ conventional-changelog-core > conventional-changelog-writer  │
│               │ > handlebars                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1325                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 9 high severity vulnerabilities in 930414 scanned packages
  run `npm audit fix` to fix 9 of them.
```

</details>

### Requesting Review

cc: @ericsciple, @joshmgross , @bryanmacfarlane as last three people to touch this file

### CODE REVIEW

**Comment by joshmgross** [comment]
We’ll need to bump the package versions if we want to publish these changes

**Comment by francisfuzz** [comment]
> We’ll need to bump the package versions if we want to publish these changes

@joshmgross - Great point! I opened a PR against my own fork patching all 6 packages: 

https://github.com/francisfuzz/toolkit/pull/1

If that's what you had in mind, I'll merge it so this PR's compare HEAD will automatically be updated. Otherwise, let me know what you had in mind and I'll make those changes 👌

**Comment by bryanmacfarlane** [comment]
I've invited @francisfuzz and @konradpabjan as contributors until actions org PR goes through

**Comment by bryanmacfarlane** [comment]
@francisfuzz - can we add the changes to package.json to this PR?

**Comment by bryanmacfarlane** [comment]
I'm taking a look

**Comment by bryanmacfarlane** [comment]
Those aren't actually dependencies of the toolkit.  They are dependencies of dependencies of dependencies and they are in the test reporting portion (not the runtime or toolkit functions).

I guess its an interesting question about whether we should be bumping dependencies of a dependency.

npm list shows:

```bash
│   │ │ ├─┬ @jest/transform@24.9.0
...
│   │ │ ├─┬ istanbul-reports@2.2.6
│   │ │ │ └─┬ handlebars@4.5.1
...
│   │ │ │   └─┬ uglify-js@3.6.8
```

So, isn't it jests role to update their dependency which is out of date with issues and then we update jest?  (this is likely because if sliding dependencies).

Let me try and update jest and see if that fixes it (instead of modifying the dep of a dep etc).

Thoughts?

**Comment by konradpabjan** [comment]
Looks like `istanbul-reports` recently got rid of handlebars in there alpha version all together (3.X): https://github.com/istanbuljs/istanbuljs/blob/5319df684b508ff6fb19fe8b9a6147a3c5924e4b/packages/istanbul-reports/CHANGELOG.md#bug-fixes-1

Version 3.X is still not out though but if we wait then it should get resolved upstream once the new version hits. Going from 2.2.6 -> 3.X.X could take some time though and there appear to be breaking changes so it could be a long time before we see 3.X show up in jest.

**Comment by bryanmacfarlane** [comment]
had a chat with @ericsciple and even thought it's a dep of a dep of a dep, npm audit is updating those dependencies within the constraints of those dependency definitions (carrots).  So it's in conformance to the acceptable semvers defines.  So this is 👍

**Comment by bryanmacfarlane** [comment]
There's no need to bump the versions of all the packages because those aren't changing.  It's just changing the tooling in the root of the repo so I think it's good as is.

**Comment by bryanmacfarlane** [comment]
I'm going to create another PR after this to integrate npm audit with the CI process

**Comment by bryanmacfarlane** [comment]
https://github.com/actions/toolkit/pull/280 correctly failed per https://github.com/actions/toolkit/pull/280/checks?check_run_id=372960572.  

After merging this it should succeed.

**Pull request merged**
