### PR TITLE
Fix broken line buffers

### PR DESCRIPTION
**Pull request by qRoC**
Line buffer does not work on big strings.

### CODE REVIEW

**Comment by luketomlinson** [comment]
hey @qRoC, thanks for the PR! Do you have some sample output to demonstrate the issue that your changes would fix? I think it could be helpful to have a test to demonstrate the behavior. I was having trouble reproducing this behavior over in #749, so I'd be curious if you have a consistent scenario that breaks.

**Comment by qRoC** [comment]
The chunk in `data` event contains either one line of output or a line with the size of the buffer.

So to reproduce this error, just print a string larger than the buffer size.

Case: `cargo build` with json output.

I fixed this in https://github.com/fibiol/cargo-actions/commit/fff2c76cd9c066e3d25b17e99052ca96439ee35c

**Comment by luketomlinson** [comment]
hi @qRoC, thank you for your response. I did some more digging, and I think this is a good fix for #749. If we can add a test for this case I will feel confident approving this. If you don't want to take that on, I am happy to take a stab at my own implementation.

**Review by luketomlinson — APPROVED** [review]
Thanks for this PR @qRoC! I'm going to go ahead and merge and add a test later.

**Pull request merged**
