### PR TITLE
Add 'repository.directory' to package manifests

### PR DESCRIPTION
**Pull request by hmarr**
This is supported by npm ([docs](https://docs.npmjs.com/files/package.json#repository)). It can help tools like Dependabot figure out what's changed between versions.

### CODE REVIEW

**Comment by xt0rted** [comment]
This change was mentioned in https://github.com/actions/toolkit/issues/104#issuecomment-529155474. I think for it to fully work with dependabot the `RELEASES.md` files also need to be renamed.

**Comment by hmarr** [comment]
The other option is just supporting those files in Dependabot. https://github.com/dependabot/dependabot-core/pull/1392 adds support for that.

**Comment by hmarr** [comment]
Apparently dependabot looks for filenames *containing* those strings (case-insensitive), so it should already work as `release` is in the list.

**Comment by bryanmacfarlane** [comment]
@xt0rted - it sounds like we're good then since it looks for files that contain `release`.  OK?

**Comment by xt0rted** [comment]
@bryanmacfarlane yea, this should be all that's needed for dependabot to pickup the change logs.

**Pull request merged**
