### PR TITLE
Add a bit of detail to tool-cache README.md

### PR DESCRIPTION
**Pull request by joshhale**
@joshmgross cleared up some fairly broad misunderstandings I had about the tool-cache. This is a suggested amendment to the `README.md` that would have set me on the right foot to begin with.

### CODE REVIEW

**Comment by joshhale** [comment]
@joshmgross Should I cc a team to get some attention on this PR?

**Comment by joshmgross** [comment]
cc: @hross and @bryanmacfarlane

**Comment by bryanmacfarlane** [comment]
I have an existing doc that details how this works.  I'm going to open source it and add it to this repo.  So I think we should hold this PR for now.  I'll create another PR and share

**Comment by bryanmacfarlane** [comment]
https://github.com/actions/toolkit/issues/363

**Comment by joshhale** [comment]
Sounds good to me. It will be nice to add a link from this README to the new doc once it's added.

**Pull request closed without merging**
