### PR TITLE
Fix endColumn documentation

### PR DESCRIPTION
**Pull request by martincostello**
Change "start" to "end".

### CODE REVIEW

**Review by luketomlinson — APPROVED** [review]
🔍 Thanks @martincostello!

**Comment by martincostello** [comment]
Just noticed this is still open 3 months later - could you merge it?

**Comment by martincostello** [comment]
Could someone merge this? Maybe @pdotl?

**Comment by pdotl** [comment]
Thank you for the contribution @martincostello 👍

**Pull request merged**
