### PR TITLE
core: add helpers for working with paths across OSes

### PR DESCRIPTION
**Pull request by sethvargo**

### CODE REVIEW

**Review by konradpabjan — COMMENTED** [review]
Overall this looks great!

Could you go ahead and document these new functions in the `README` for `@actions/core`: https://github.com/actions/toolkit/tree/main/packages/core

**Comment by sethvargo** [comment]
@konradpabjan done

**Review by konradpabjan — APPROVED** [review]
Looks good to me! 

I'll differ for the final approval from @thboop before merging in

**Review by thboop — APPROVED** [review]
LGTM thanks for the contribution!

**Comment by RA80533** [comment]
What is the purpose of these functions compared to those available from the native Path module ([link])?

[link]: https://nodejs.org/api/path.html

**Comment by sethvargo** [comment]
Hi @RA80533 these functions are for converting from platform-specific or non-platform-specific paths, regardless of the underlying operating system.

**Pull request merged**
