### PR TITLE
Closes: #981

### PR DESCRIPTION
**Pull request by frank-dspeed**
Moved dependencies around to remove circular dependencie cycles with the final goal to transpil to ESM without worrys

#981

### CODE REVIEW

**Comment by frank-dspeed** [comment]
@yaananth please look into #981 this issue why did you remove the review request? is there a valid reason that i did not see?

**Comment by yaananth** [comment]
Service team doesn't own this, there are other teams still in review list, they should be able to get back to you

**Comment by Bogdanp** [comment]
Could this be merged? I use a bundler in [Bogdanp/setup-racket](https://github.com/Bogdanp/setup-racket) and the circular dependency makes it [impossible](https://github.com/Bogdanp/setup-racket/pull/57) for me to upgrade from `@actions/core` 1.5.

**Comment by Zxilly** [comment]
2 years passed but no one works on this.

**Comment by frank-dspeed** [comment]
@Zxilly ya Microsoft does not care thats why i do not use it anymore github is dead.

**Pull request closed without merging**
